version: '3'
services:
  app:
    cap_add:
      - 'SYS_ADMIN'
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'
    command: npm run test-coverage:complete
